version: '2.3'

services:
  gpukerastf:
    ports:
      - 8888:8888
    env_file: ./.env
    build:
      context: ./gpukerastf
    volumes:
      - ../notebooks:/notebooks
    command: bash -c "export PYTHONPATH=/notebooks/ && jupyter notebook --notebook-dir /notebooks/ --ip=* --port=8888 --allow-root --NotebookApp.token='' --log-level=DEBUG --no-browser --debug"

  # postgres9:
  #     ports:
  #       - 5434:5432
  #     env_file: ./.env
  #     build:
  #       context: ./postgres9
  #     volumes:
  #       - ./postgres9/data/db-data:/var/lib/postgresql/data
