version: '2.3'

services:
  gpu:
    ports:
      - 8888:8888
    env_file: ./.env
    runtime: nvidia
    user: ${CURRENT_UID}
    build:
      context: ./gpu
    volumes:
      - ../notebooks:/notebooks
    command: bash -c "export PYTHONPATH=/notebooks/ && jupyter notebook --notebook-dir /notebooks/ --ip=* --port=8888 --NotebookApp.token='' --log-level=DEBUG --no-browser --debug"
